name: 機能追加・改善
description: 新機能の追加や既存機能の改善を提案
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        新機能や改善案を提案するためのテンプレートです。

  - type: dropdown
    id: priority
    attributes:
      label: 優先度
      description: この機能の重要度を選択してください
      options:
        - 高（すぐに必要）
        - 中（あると便利）
        - 低（将来的に）
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 解決したい課題
      description: どんな問題を解決したいですか？
      placeholder: 例：グループが100件あると目的のグループを探しにくい
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 提案する解決策
      description: どのような機能があれば解決できますか？
      placeholder: 例：グループにタグを付けて分類したい
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: 代替案（あれば）
      description: 他に考えられる解決方法はありますか？
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: その他・補足
      description: 参考情報や関連リンクなど
    validations:
      required: false
